name: Build
on: [push, pull_request]

jobs:

  build-macos:
    name: Build macOS
    if: true

    strategy:
      fail-fast: false
      matrix:
        runner: [ 'macos-11', 'macos-12', 'macos-13' ]
        buildtype: [ 'release' ]

    runs-on: ${{ matrix.runner }}

    steps:

      - name: Test
        run: ls -la /Applications
