name: Build
on: [push, pull_request]

env:
  nasm_version: '3.01'

  yasm_version: '1.3.0'

  win_flex_bison_version: '2.5.25'

  pkgconf_version: '2.5.1'

  proxy_libintl_version: '0.5'

  getopt_win_version: '2.42.0'

  zlib_version: '1.3.2'

  openssl_version: '4.0.0'

  gmp_version: '6.2.1-4'
  
  nettle_version: '3.10.1_release_20241230'

  gnutls_version: '3.8.8'

  libpng_version: '1.6.58'

  libjpeg_turbo_version: '3.1.4.1'

  pcre2_version: '10.47'

  bzip2_version: '1.0.8'

  xz_version: '5.8.3'

  brotli_version: '1.2.0'

  icu4c_version: '78.3'

  pixman_version: '0.46.4'

  expat_version: '2.8.0'

  boost_version: '1.91.0'

  libxml2_version: '2.15.3'

  nghttp2_version: '1.69.0'

  dlfcn_version: '1.4.2'

  libpsl_version: '0.21.5'

  orc_version: '0.4.42'

  sqlite3_version: '3530000'

  glib_version: '2.88.0'

  libsoup_version: '3.6.6'

  glib_networking_version: '2.80.1'

  freetype_version: '2.14.3'

  harfbuzz_version: '14.2.0'

  jasper_version: '4.2.9'

  tiff_version: '4.7.1'

  libwebp_version: '1.6.0'

  libogg_version: '1.3.6'

  libvorbis_version: '1.3.7'

  flac_version: '1.5.0'

  wavpack_version: '5.9.0'

  opus_version: '1.5.2'

  opusfile_version: '0.12'

  speex_version: '1.2.1'

  mpg123_version: '1.33.4'

  lame_version: '3.100'

  twolame_version: '0.4.0'

  musepack_version: '475'

  libopenmpt_version: '0.8.6'

  libgme_version: '0.6.5'

  faad2_version: '2.11.2'

  faac_version: '1.50'

  fdk_aac_version: '2.0.3'

  utfcpp_version: '4.0.9'

  taglib_version: '2.2.1'

  libbs2b_version: '3.1.0'

  libebur128_version: '1.2.6'

  fftw_source_version: '3.3.10'

  fftw_mingw_version: '3.3.11.20'

  ffmpeg_version: '8.0.1'

  chromaprint_version: '1.6.0'

  gstreamer_version: '1.28.2'

  gstreamer_plugins_rs_version: '0.15.1'

  qt_version: '6.11.0'

  kdsingleapplication_version: '1.2.1'

  sparsehash_version: '2.0.4'

  pe_parse_version: '2.1.1'

  max_releases: '6'

  curl_options: '-f -O -L --connect-timeout 60 -m 900 --retry 15 --retry-delay 10 --retry-max-time 300 --retry-all-errors'

  sourceforge_mirror1: 'downloads.sourceforge.net'
  sourceforge_mirror2: 'netix.dl.sourceforge.net'

  qt_mirror: 'mirrors.ukfast.co.uk/sites/qt.io'

  cmake_loglevel: 'DEBUG'

  cmake_generator: 'Ninja'

  PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: '1'

  PKG_CONFIG_ALLOW_SYSTEM_LIBS: '1'

  CL: '-MP'


jobs:

  setup:
    name: Setup
    if: (!contains(github.event.head_commit.message, 'skip ci'))
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{steps.set_release_tag.outputs.release_tag}}
    steps:
      - name: Set release tag
        id: set_release_tag
        shell: bash
        run: echo "release_tag=release-$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

  build:
    name: Build Windows MSVC
    needs:
      - setup

    if: (!contains(github.event.head_commit.message, 'skip ci'))

    strategy:

      matrix:
       include:
         - name: "Windows x86_64 debug"
           runner: windows-2022
           arch: x86_64
           buildtype: debug

         - name: "Windows x86_64 release"
           runner: windows-2022
           arch: x86_64
           buildtype: release

         - name: "Windows arm64 debug"
           runner: windows-11-arm
           arch: arm64
           buildtype: debug

         - name: "Windows arm64 release"
           runner: windows-11-arm
           arch: arm64
           buildtype: release

    runs-on: ${{matrix.runner}}

    steps:

      - name: Set buildtype
        shell: bash
        run: echo "buildtype=$(echo ${{matrix.buildtype}} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set cmake and meson buildtype
        shell: bash
        run: |
          echo "cmake_buildtype=$(echo ${{env.buildtype}} | sed 's/.*/\u&/')" >> $GITHUB_ENV
          echo "meson_buildtype=${{env.buildtype}}" >> $GITHUB_ENV

      - name: Set prefix path
        shell: bash
        run: |
          echo "prefix_path_backslash=c:\strawberry_msvc_${{matrix.arch}}_${{env.buildtype}}" >> $GITHUB_ENV
          echo "prefix_path_backslash2=c:\\\\strawberry_msvc_${{matrix.arch}}_${{env.buildtype}}" >> $GITHUB_ENV
          echo "prefix_path_forwardslash=c:/strawberry_msvc_${{matrix.arch}}_${{env.buildtype}}" >> $GITHUB_ENV
          echo "prefix_path_unix=/c/strawberry_msvc_${{matrix.arch}}_${{env.buildtype}}" >> $GITHUB_ENV

      - name: Show SDK versions
        shell: bash
        run: ls -la "c:/Program Files (x86)/Windows Kits/10/include"

      - name: Set SDK version
        if: matrix.arch != 'arm64'
        shell: bash
        run: echo "sdk_version=10.0.22621.0" >> $GITHUB_ENV

      - name: Set SDK version
        if: matrix.arch == 'arm64'
        shell: bash
        run: echo "sdk_version=10.0.26100.0" >> $GITHUB_ENV

      - name: Set lib postfix
        if: env.buildtype == 'debug'
        shell: bash
        run: echo "lib_postfix=d" >> $GITHUB_ENV

      - name: Set arch variables (x86_64)
        if: matrix.arch == 'x86_64'
        shell: bash
        run: |
          echo "openssl_platform=VC-WIN64A" >> $GITHUB_ENV
          echo "msbuild_platform=x64" >> $GITHUB_ENV
          echo "arch_short=x64" >> $GITHUB_ENV
          echo "arch_win=win64" >> $GITHUB_ENV
          echo "arch_bits=64" >> $GITHUB_ENV
          echo "libdir=lib64" >> $GITHUB_ENV
          echo "bindir=bin64" >> $GITHUB_ENV
          echo "libjpeg_turbo_simd=ON" >> $GITHUB_ENV
          echo "boost_architecture=x86" >> $GITHUB_ENV
          echo "glib_networking_gnutls=enabled" >> $GITHUB_ENV
          echo "gst_twolame=enabled" >> $GITHUB_ENV

      - name: Set arch variables (arm64)
        if: matrix.arch == 'arm64'
        shell: bash
        run: |
          echo "openssl_platform=VC-WIN64-ARM" >> $GITHUB_ENV
          echo "msbuild_platform=arm64" >> $GITHUB_ENV
          echo "arch_short=arm64" >> $GITHUB_ENV
          echo "arch_win=win64" >> $GITHUB_ENV
          echo "arch_bits=64" >> $GITHUB_ENV
          echo "libdir=libARM64" >> $GITHUB_ENV
          echo "bindir=binARM64" >> $GITHUB_ENV
          echo "libjpeg_turbo_simd=OFF" >> $GITHUB_ENV
          echo "boost_architecture=arm" >> $GITHUB_ENV
          echo "glib_networking_gnutls=disabled" >> $GITHUB_ENV
          echo "gst_twolame=disabled" >> $GITHUB_ENV

      - name: Set extra version variables
        shell: bash
        run: |
          echo "boost_version_underscore=$(echo ${{env.boost_version}} | sed 's/\./_/g')" >> $GITHUB_ENV
          echo "glib_version_short=$(echo ${{env.glib_version}} | cut -d '.' -f 1-2)" >> $GITHUB_ENV
          echo "glib_networking_version_short=$(echo ${{env.glib_networking_version}} | cut -d '.' -f 1-2)" >> $GITHUB_ENV
          echo "libsoup_version_short=$(echo ${{env.libsoup_version}} | cut -d '.' -f 1-2)" >> $GITHUB_ENV
          echo "qt_version_short=$(echo ${{env.qt_version}} | cut -d '.' -f 1-2)" >> $GITHUB_ENV
          echo "expat_version_underscore=$(echo ${{env.expat_version}} | sed 's/\./_/g')" >> $GITHUB_ENV
          echo "libxml2_version_short=$(echo ${{env.libxml2_version}} | cut -d '.' -f 1-2)" >> $GITHUB_ENV

      - name: Set pkg-config variables
        shell: bash
        run: |
          echo "PKG_CONFIG_EXECUTABLE=${{env.prefix_path_backslash}}\bin\pkgconf.exe" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=${{env.prefix_path_backslash}}\lib\pkgconfig" >> $GITHUB_ENV

      - name: Create directories
        shell: bash
        run: mkdir -p ${{env.prefix_path_unix}}/{bin,lib,include}

      - name: Update PATH
        shell: pwsh
        run: echo "${{env.prefix_path_backslash}}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      #- name: Copy bin files
        #shell: bash
        #run: cp /c/strawberry/c/bin/{patch.exe,strip.exe,strings.exe,objdump.exe} ${{env.prefix_path_unix}}/bin

      #- name: Delete conflicting libraries
        #shell: bash
        #run: rm -rf /c/{msys64,mingw32,mingw64,clangarm64} /c/strawberry/c

      # - name: Delete conflicting icu
      #   shell: bash
      #   run: find "/c/program files (x86)/windows kits/" -type f \( -iname 'icu*.lib' -o -iname 'icu*.h' \) -print -delete


      - name: Set python version
        shell: bash
        run: echo "python_version="$(which python | cut -d '/' -f 6)"" >> $GITHUB_ENV


      - name: Cleanup PATH
        uses: egor-tensin/cleanup-path@v5
        with:
          dirs: ${{env.prefix_path_backslash}}\bin;C:\Windows;C:\Windows\system32;C:\Program Files\Git\bin;C:\Program Files\CMake\bin;C:\Program Files\GitHub CLI;C:\ProgramData\Chocolatey\bin;C:\Strawberry\perl\bin;C:\hostedtoolcache\windows\Python\${{env.python_version}}\${{env.arch_short}};C:\hostedtoolcache\windows\Python\${{env.python_version}}\${{env.arch_short}}\Scripts;C:\Users\runneradmin\.cargo\bin


      # - name: Setup Rust
      #   uses: dtolnay/rust-toolchain@stable
      #   with:
      #     toolchain: stable
      #     components: rustfmt


      # - name: Setup Python
      #   uses: actions/setup-python@v6
      #
      # - name: Install python dependencies
      #   shell: cmd
      #   run: pip install meson ninja


      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          sdk: ${{env.sdk_version}}
          vsversion: 2022


      - name: Checkout
        uses: actions/checkout@v6


      - name: Create downloads directory
        shell: cmd
        run: mkdir downloads

      - name: Create build directory
        shell: cmd
        run: mkdir build


      - name: Download FFTW (x86_64)
        if: matrix.arch == 'x86_64'
        shell: bash
        working-directory: downloads
        run: curl ${{env.curl_options}} https://github.com/strawberrymusicplayer/fftw3-mingw-cross/releases/download/${{env.fftw_mingw_version}}/fftw-x86_64-w64-mingw32-${{env.buildtype}}-${{env.fftw_mingw_version}}.tar.xz

      - name: Extract FFTW (x86_64)
        if: matrix.arch == 'x86_64'
        shell: bash
        working-directory: build
        run: tar -xvf ../downloads/fftw-x86_64-w64-mingw32-${{env.buildtype}}-${{env.fftw_mingw_version}}.tar.xz

      - name: Update fftw3.pc (x86_64)
        if: matrix.arch == 'x86_64'
        shell: bash
        working-directory: build/fftw-x86_64-w64-mingw32-${{env.buildtype}}-${{env.fftw_mingw_version}}/lib/pkgconfig
        run: |
          sed -i "s,^prefix=.*,prefix=${{env.prefix_path_forwardslash}},g" fftw3.pc
          sed -i "s,^exec_prefix=.*,exec_prefix=${{env.prefix_path_forwardslash}},g" fftw3.pc
          sed -i "s,^libdir=.*,libdir=${{env.prefix_path_forwardslash}}/lib,g" fftw3.pc
          sed -i "s,^includedir=.*,includedir=${{env.prefix_path_forwardslash}}/include,g" fftw3.pc

      - name: Generate lib (x86_64)
        if: matrix.arch == 'x86_64'
        shell: bash
        working-directory: build/fftw-x86_64-w64-mingw32-${{env.buildtype}}-${{env.fftw_mingw_version}}
        run: lib /machine:${{env.arch_short}} /def:libfftw3-3.def

      - name: Install FFTW (x86_64)
        if: matrix.arch == 'x86_64'
        shell: bash
        working-directory: build/fftw-x86_64-w64-mingw32-${{env.buildtype}}-${{env.fftw_mingw_version}}
        run: |
          cp -v include/*.h ${{env.prefix_path_unix}}/include/
          cp -v bin/*.dll ${{env.prefix_path_unix}}/bin/
          cp -v lib/*.lib ${{env.prefix_path_unix}}/lib/
          cp -v lib/pkgconfig/*.pc ${{env.prefix_path_unix}}/lib/pkgconfig/


      - name: Download FFTW (arm64)
        if: matrix.arch == 'arm64'
        shell: bash
        working-directory: downloads
        run: |
          curl ${{env.curl_options}} https://www.fftw.org/fftw-${{env.fftw_source_version}}.tar.gz || \
          curl ${{env.curl_options}} https://${{env.sourceforge_mirror1}}/project/fftw/fftw/${{env.fftw_source_version}}/fftw-${{env.fftw_source_version}}.tar.gz || \
          curl ${{env.curl_options}} https://${{env.sourceforge_mirror2}}/project/fftw/fftw/${{env.fftw_source_version}}/fftw-${{env.fftw_source_version}}.tar.gz

      - name: Extract FFTW (arm64)
        if: matrix.arch == 'arm64'
        shell: bash
        working-directory: build
        run: tar -xf ../downloads/fftw-${{env.fftw_source_version}}.tar.gz

      - name: Extract FFTW (arm64)
        if: matrix.arch == 'arm64'
        shell: bash
        working-directory: build/fftw-${{env.fftw_source_version}}
        run: patch -p1 < ../../patches/fftw-fixes.patch

      - name: Configure FFTW (arm64)
        if: matrix.arch == 'arm64'
        shell: cmd
        working-directory: build/fftw-${{env.fftw_source_version}}
        run: cmake --log-level="${{env.cmake_loglevel}}" -S . -B build -G "${{env.cmake_generator}}" -DCMAKE_BUILD_TYPE="${{env.cmake_buildtype}}" -DCMAKE_INSTALL_PREFIX=${{env.prefix_path_backslash}} -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF -DENABLE_AVX=ON -DENABLE_AVX2=OFF -DENABLE_SSE=ON -DENABLE_SSE2=ON -DENABLE_THREADS=ON -DWITH_COMBINED_THREADS=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build FFTW (arm64)
        if: matrix.arch == 'arm64'
        shell: cmd
        working-directory: build/fftw-${{env.fftw_source_version}}/build
        run: cmake --build .

      - name: Install FFTW (arm64)
        if: matrix.arch == 'arm64'
        shell: cmd
        working-directory: build/fftw-${{env.fftw_source_version}}/build
        run: cmake --install .

      - name: Check fftw
        shell: cmd
        run: pkg-config fftw3 --libs --cflags

