---

name: Test
on:
  push:
jobs:
  build-openbsd:
    name: Build OpenBSD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Build OpenBSD
      id: build-openbsd
      uses: vmactions/openbsd-vm@v1.1.6
      with:
        usesh: true
        mem: 4096
        prepare: pkg_add rapidjson
        run: find /usr -iname '*RapidJSON*'
